cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>', views.full_remove, name='full_remove'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',
         UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='index'),

    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product.views import *

app_name = 'product'

urlpatterns = [
    path('', ProductLV.as_view(), name='list'),
    path('<int:pk>/', ProductDV.as_view(), name='detail'),
    path('search/', SearchLView.as_view(), name='search'),
    # Example: /product/tag/
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    # Example: /product/tag/tagname/
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
]

cart/models.py
from django.db import models
from product.models import Product

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField('CART_ID', max_length=250, blank=True)
    date_added = models.DateField('DATE_ADDED', auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField('QUANTITY')
    active = models.BooleanField('ACTIVE', default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return self.product

cart/views.py
from django.core import exceptions
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Product
from .models import *
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    
    return render(request, 'cart/cart.html', dict(cart_items = cart_items, total=total, counter=counter))

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block extra-style %}
<style>
    a:hover,
    a:focus {
        text-decoration: none;
        outline: none;
        color: #4971FF;
    }
</style>
{% endblock %}


{% block content %}

<!-- Breadcrumb End -->
<div class="breadcrumb-option set-bg" data-setbg="{% static 'img/notebook_main.jpg' %}">
    <div class="container" style="margin: 10px;">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>장바구니</h2>
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <span>장바구니</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Begin -->

<section class="car spad">
    <div class="container">
        <!-- 장바구니 리스트 -->
        <div class="row">
            <div class="col-12">
            {% if not user.is_active %}
                <h2 style="text-align: center;"><strong>로그인이 필요합니다.</strong></h2>
                <br>
            </div>
            <div class="col-12">
                <h4 style="text-align: center;"><a href="{% url 'login' %}">로그인 하러가기</a></h4>
            </div>
            {% else %}
            {% if not cart_items %}
            <h2 style="text-align: center;"><strong>장바구니가 비어있습니다.</strong></h2>
            <br>
        </div>
        <div class="col-12">
            <h4 style="text-align: center;"><a href="{% url 'product:list' %}">쇼핑하러가기</a></h4>
        </div>
        {% else %}

        {% for cart_item in cart_items %}
        <div class="col-lg-12 col-md-12" style="padding: 0 50px 0 50px;">
            <div class="car__item" style="height: max-content;">
                <div class="car__item__text">
                    <div class="row" style="margin-left: 0px;">
                        <div class="col-3">
                            <a href="{{ cart_item.product.get_absolute_url }}">
                                <img src="{{ cart_item.product.imageURL }}" alt=""
                                    style="border-right: 1px solid #ebebeb; border-radius: 2px 2px 0 0; padding-left: 15px; padding-right: 15px;">
                            </a>
                        </div>
                        <div class="col-9" style="padding-left: 0px;">
                            <div class="car__item__text__inner" style="height: 174px;">
                                <br>
                                <h5 style="font-size: 25px;"><strong>{{ cart_item.product.name }}</strong></h5>
                                <br>
                                <ul>
                                    <li style="font-size: 20px;"><span>상품 번호: {{ cart_item.product.id }}</span></li>
                                    <li style="font-size: 20px;">개당 가격 : {{ cart_item.product.price | intcomma }} 원</li>
                                    <li style="font-size: 20px;"><span>주문량 : {{ cart_item.quantity }} 개</span></li>
                                    <li style="font-size: 20px; color: #4971FF;">총 가격 : {{ cart_item.sub_total | intcomma }}원</li>
                                </ul>
                            </div>
                            <div class="car__item__price" style="text-align: left; padding-left: 20px;">
                                <h5 style="font-size: 18px;">수량 변경 &nbsp;&nbsp;&nbsp;
                                    <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i
                                            class="fa fa-plus-circle" style="font-size: 20px;"></i></a>&nbsp;&nbsp;
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i
                                            class="fa fa-minus-circle" style="font-size: 20px;"></i></a>&nbsp;
                                </h5>
                                <br>

                                <h5 style="font-size: 18px;">삭제 &nbsp;&nbsp;&nbsp;<a
                                        href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash"
                                            style="font-size: 20px;"></i></a>&nbsp;</h5>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-12 text-center">
        <table class="table">
            <thead>
                <tr>
                    <th style="font-size: 20px;">전체 합계</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td scope="row" style="font-size: 20px;">
                        전체 주문 금액 : <strong style="color: red;"> 총 {{ total | intcomma }}원</strong>
                    </td>
                </tr>
            </tbody>
        </table>

        <div>

            <a href="{% url 'product:list' %}" class="primary-btn">
                <i class="fa fa-cart-plus"></i>
                쇼핑 계속하기</a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="#" class="primary-btn">
                <i class="fa fa-credit-card"></i>
                결제하기</a>

        </div>
        {% endif %}
        {% endif %}
    </div>
    </div>
</section>

{% endblock %}