cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>', views.full_remove, name='full_remove'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',
         UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='index'),

    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product.views import *

app_name = 'product'

urlpatterns = [
    path('', ProductLV.as_view(), name='list'),
    path('<int:pk>/', ProductDV.as_view(), name='detail'),
    path('search/', SearchLView.as_view(), name='search'),
    # Example: /product/tag/
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    # Example: /product/tag/tagname/
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
]

templates/taggit/taggit_cloud.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Breadcrumb End -->
<div class="breadcrumb-option set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Car Listing</h2>
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <span>About</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Begin -->
<h1>Product Tag Cloud</h1>
<br>
<div class="tag-cloud">
    {% load taggit_templatetags2_tags %}
    {% get_tagcloud as tags %}
    {% for tag in tags %}
    <span class="tag-{{ tag.weight|floatformat:0 }}">
        <a href="{% url 'product:tagged_object_list' tag.name %}">
            {{ tag.name }}({{ tag.num_times }})</a>
    </span>
    {% endfor %}
</div>
{% endblock %}

templates/taggit/taggit_product_list.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block extra-style %}
<style>
    a:hover,
    a:focus {
        text-decoration: none;
        outline: none;
        color: #4971FF;
    }

    .btn-secondary.focus,
    .btn-secondary:focus {
        color: black;
        background-color: #f7f7f7;
        border-color: #545b62;
        box-shadow: 0 0 0 0.2rem rgb(130 138 145 / 50%);
    }

    .btn-secondary:not(:disabled):not(.disabled).active,
    .btn-secondary:not(:disabled):not(.disabled):active,
    .show>.btn-secondary.dropdown-toggle {
        color: black;
        background-color: #f7f7f7;
        border-color: #4e555b;
    }

    .btn-secondary {
        color: black;
        background-color: #e3e7eb;
        border-color: #6c757d;
    }

    .col-3 img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }


    body {
        padding: 40px 0 0 0;
    }

    .value {
        position: absolute;
        top: 30px;
        left: 50%;
        margin: 0 0 0 -20px;
        width: 40px;
        text-align: center;
        display: block;

        /* optional */

        font-weight: normal;
        font-family: Verdana, Arial, sans-serif;
        font-size: 14px;
        color: #333;
    }

    .price-range-both.value {
        width: 100px;
        margin: 0 0 0 -50px;
        top: 26px;
    }

    .price-range-both {
        display: none;
    }

    .value i {
        font-style: normal;
    }

    .ui-slider {
        position: relative;
        text-align: left;
    }

    .ui-slider .ui-slider-handle {
        position: absolute;
        z-index: 2;
        width: 1.2em;
        height: 1.2em;
        cursor: default;
        -ms-touch-action: none;
        touch-action: none;
    }

    .ui-slider .ui-slider-range {
        position: absolute;
        z-index: 1;
        font-size: .7em;
        display: block;
        border: 0;
        background-position: 0 0;
    }

    .ui-slider.ui-state-disabled .ui-slider-handle,
    .ui-slider.ui-state-disabled .ui-slider-range {
        filter: inherit;
    }

    .ui-slider-horizontal {
        height: .8em;
    }

    .ui-slider-horizontal .ui-slider-handle {
        top: -.3em;
        margin-left: -.6em;
    }

    .ui-slider-horizontal .ui-slider-range {
        top: 0;
        height: 100%;
    }

    .ui-slider-horizontal .ui-slider-range-min {
        left: 0;
    }

    .ui-slider-horizontal .ui-slider-range-max {
        right: 0;
    }

    .ui-slider-vertical {
        width: .8em;
        height: 100px;
    }

    .ui-slider-vertical .ui-slider-handle {
        left: -.3em;
        margin-left: 0;
        margin-bottom: -.6em;
    }

    .ui-slider-vertical .ui-slider-range {
        left: 0;
        width: 100%;
    }

    .ui-slider-vertical .ui-slider-range-min {
        bottom: 0;
    }

    .ui-slider-vertical .ui-slider-range-max {
        top: 0;
    }

    .range .ui-slider-handle {
        width: 18px;
        height: 18px;
        top: -7px;
        background: orange;
        /* border-radius: 50%; */
        box-shadow: 0 0 7px 1px rgba(0, 0, 0, 0.1);
        transform: translateX(0);
        outline: none;
        cursor: pointer;
    }

    .ui-slider-handle-value {
        font-size: 10px;
        min-width: 50px;
        text-align: center;
        position: absolute;
        padding-left: 5px;
        padding-right: 5px;
        top: 0;
        left: 50%;
        transform: translate(-50%, calc(-100% - 10px));
        box-shadow: 0 0 7px 1px rgba(0, 0, 0, 0.1);
        /* background-color: #fff; */
        color: black;
    }


    .ui-slider-handle-value::after {
        content: "";
        position: absolute;
        bottom: -3px;
        left: 50%;
        transform: translateX(-50%) rotate(-45deg);
        border: 3px solid transparent;
        border-left-color: #fff;
        border-bottom-color: #fff;
        box-shadow: -7px 6px 7px 0 rgba(0, 0, 0, 0.1);
    }

    .range__slider {
        border: none;
        background: #aaaaaa;
        border-radius: 0;
        margin-top: 58px;
        height: 7px;
    }

    .range__label {
        font-size: 15px;
        line-height: 20px;
        color: #808080;
    }

    .range__input {
        /* width: 100px;
        height: 35px;
        box-sizing: border-box;
        border-radius: 4px;
        border: 1px solid #808080;
        display: block;
        text-align: center;
        font-size: 26px;
        color: #000000; */
        height: 35px;
        width: 100%;
        font-size: 15px;
        color: #727171;
        padding-left: 10px;
        border: 1px solid #ebebeb;
        background: #ffffff;
    }

    .range__text-inputs {
        display: flex;
        justify-content: space-between;
    }

    .range__wrapper {
        text-align: left;
        line-height: 16px;
    }

    .ui-slider-range {
        background: #ee3643;
    }

    input[type="number"]::-webkit-outer-spin-button,
    input[type="number"]::-webkit-inner-spin-button {
        opacity: 1;
    }
</style>
{% endblock %}

{% block content %}

<!-- Breadcrumb End -->
<div class="breadcrumb-option set-bg" data-setbg="{% static 'img/notebook_main.jpg' %}">
    <div class="container" style="margin: 10px;">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Car Listing</h2>
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <span>About</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Begin -->

<!-- Car Section Begin -->
<section class="car spad">
    <div class="container" style="max-width: 1200px;">
        <div class="row">

            <div class="col-lg-12">

                {% block list %}
                <!-- 정렬 필터 -->
                <div class="car__filter__option">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <h6 style="line-height: 35px; font-size: 20px;"><strong>{{ tagname }}</strong></h6>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="car__filter__option__item car__filter__option__item--right">
                                <h6>Sort By</h6>
                                <select>
                                    <option value="">Price: Highest Fist</option>
                                    <option value="">Price: Lowest Fist</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- 노트북 리스트 -->
                <div class="row">
                    {% for product in object_list %}
                    <div class="col-lg-12 col-md-12">
                        <div class="car__item" style="height: max-content;">
                            <!-- <div class="car__item__pic__slider owl-carousel"> -->
                            <!-- <img src="{{ product.imageURL }}" alt=""> -->
                            <!-- <img src="{{ product.imageURL }}" alt="">
                                <img src="{{ product.imageURL }}" alt="">
                                <img src="{{ product.imageURL }}" alt=""> -->
                            <!-- </div> -->
                            <div class="car__item__text">

                                <div class="row" style="margin-left: 0px;">
                                    <div class="col-3">
                                        <img src="{{ product.imageURL }}" alt=""
                                            style="border-right: 1px solid #ebebeb; border-radius: 2px 2px 0 0; padding-left: 15px; padding-right: 15px;">
                                    </div>
                                    <div class="col-9" style="padding-left: 0px;">
                                        <div class="car__item__text__inner">
                                            <div class="label-date">{{ product.maker }}</div>
                                            <h5><strong>{{ product.name }}</strong></h5>
                                            <ul>
                                                <li style="font-size: 12px;"><span>{{ product.cpu }}</span></li>
                                                <li style="font-size: 12px;">{{ product.ram }} GB</li>
                                                <li style="font-size: 12px;"><span>{{ product.gpu }}</span></li>
                                                <li style="font-size: 12px;">{{ product.volume }}</li>
                                            </ul>

                                            <ul>
                                                <li style="font-size: 12px;"><span>{{ product.sw_os }}</span></li>
                                                <li style="font-size: 12px;">{{ product.display }}인치</li>
                                                <li style="font-size: 12px;"><span>{{ product.weight }}kg</span></li>
                                                <li style="font-size: 12px;">배터리 {{ product.battery }}Wh</li>
                                            </ul>
                                        </div>
                                        <div class="car__item__price">
                                            <span class="car-option" style="border-right: 1px solid #ebebeb;"><a
                                                    href="{% url 'product:detail' product.id %}">상세보기</a></span>
                                            {% if product.price < 1 %} <h6>임시품절</h6>
                                                {% else %}
                                                <h6>{{ product.price|intcomma }}<span>원</span></h6>
                                                {% endif %}
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!-- 기존 페이지네이션 -->
                <!-- <div class="pagination__option">
                    <a href="#" class="active">1</a>
                    <a href="#">2</a>
                    <a href="#">3</a>
                    <a href="#"><span class="arrow_carrot-2right"></span></a>
                </div> -->

                <!-- 나의 페이지네이션 -->
                <div class="pagination__option">
                    {% include 'pagination.html' %}
                </div>
                {% endblock %}

            </div>
        </div>
    </div>
</section>
<!-- Car Section End -->

{% endblock %}